[package]
cairo-version = "=2.12.2"
name = "dojo_sheep_a_sheep"
version = "1.0.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate"
initialize = "sozo execute dojo_sheep_a_sheep-sheep_a_sheep_actions initialize_game_settings --wait"
start-game = "sozo execute dojo_sheep_a_sheep-sheep_a_sheep_actions start_new_game --wait"
daily-challenge = "sozo execute dojo_sheep_a_sheep-sheep_a_sheep_actions start_daily_challenge --wait"


[dependencies]
dojo = "1.7.0"
dojo_cairo_macros = "1.7.0"
starknet = "2.12.2"

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dev-dependencies]
cairo_test = "=2.12.2"
dojo_cairo_test = "1.7.0"

[profile.slot]
